version: '3'

services:
  categoryservice:
    build:
      context: ./categoryservice
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ./categoryservice:/app
  assetservice:
    build:
      context: ./assetservice
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./assetservice:/app
  retrieveimageservice:
    build: 
      context: ./getimageservice
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    volumes:
      - ./getimageservice:/app
  eventbus:
    build:
      context: ./event-bus
    ports:
      - "3005:3005"
    volumes:
      - ./event-bus:/app
  mongodb:
    image: mongo 
    ports:
      - "27017:27017"


  