version: '3'

services:
  categoryservice:
    build:
      context: ./categoryservice
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./categoryservice:/app
  assetservice:
    build:
      context: ./assetservice
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ./assetservice:/app
  mongodb:
    image: mongo 
    ports:
      - "27017:27017"


  